name: Cloud Resume API
on: push
jobs: 
  build: 
    name: Build and Deploy
    runs-on: ubuntu-latest 
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}   
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
